### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'send_feedback'

### ISSUE THREAD

**Issue by L422Y** [ktnrg45/pyremoteplay#10]
When attempting to call `device.controller.button("CIRCLE", "TAP")` I am getting:

```
AttributeError: 'NoneType' object has no attribute 'send_feedback'
```

I've tried with and without `device.controller.start()`, there's no error when I call the `stick` method, I also tried lower case "circle" and "tap", this occurs on Ubuntu and macOS, not sure if I am initializing correctly or not, the examples don't give a lot of guidance yet on how to do things properly.

```
ip_address = 'X.X.X.X' # ip address of Remote Play device
device = start(ip_address)
time.sleep(1) # prevent race condition
#device.controller.start()
print(device.controller.buttons())
while True:
    print('.')
    device.controller.stick("left", point=(-0.5, -0.5))
    device.controller.button("CIRCLE", "TAP")
    # print(device.controller)
    time.sleep(3)
```

**Comment by ktnrg45** [comment]
You are seeing a race condition. Essentially you would have to sleep for longer after starting. As of 0.7.1, there are new waiters for this. You can review the updated examples or documentation for additional info.
