### ISSUE TITLE
How to get video frames as images

### ISSUE THREAD

**Issue by ccarterc** [ktnrg45/pyremoteplay#12]
I am trying to modify `client example` so I can get video frames and feed them into another system.  Ideally these would be readable by cv2.  I would like to setup a machine learning experiment and this library seems perfect for it!  

I have looked at a lot of the source code, but I still am unable to get an image that can be converted to a jpeg or png.  I am open to other solutions, but ultimately need a video frame -> image that can be ingested by an ML algorithm.  I was unable to get any video frames from the `async client example`.  In the `client example` I have been unsuccessful in using the `devices.session.receiver.video_frames` for anything useful.

**Comment by ktnrg45** [comment]
The video frames are PYAV Video Frames. I would read its [documentation](https://pyav.org/docs/develop/api/video.html#module-av.video.frame). There are multiple ways of using these frames
