### ISSUE TITLE
installing error "pip install pyremoteplay[gui]"   on Windows 11

### ISSUE THREAD

**Issue by Zhangdaoning** [ktnrg45/pyremoteplay#2]
PS C:\Users\31378> pip install pyremoteplay[gui]
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyremoteplay[gui] in c:\users\31378\appdata\roaming\python\python310\site-packages (0.3.1)
Requirement already satisfied: pyjerasure>=1.0.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (1.0.0)
Requirement already satisfied: requests>=2.25.1 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (2.27.1)
Requirement already satisfied: pyee>=8.1.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (9.0.4)
Requirement already satisfied: asyncudp>=0.6.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (0.6.0)
Requirement already satisfied: protobuf3>=0.2.1 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (0.2.1)
Requirement already satisfied: pyps4-2ndscreen>=1.2.1 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (1.3.1)
Requirement already satisfied: protobuf>=3.15.3 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (3.20.0)
Requirement already satisfied: cryptography>=3.4.6 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (36.0.2)
Collecting sounddevice>=0.4.4
  Using cached sounddevice-0.4.4-py3-none-win_amd64.whl (195 kB)
Collecting PyOpenGL==3.1.5
  Using cached PyOpenGL-3.1.5-py3-none-any.whl (2.4 MB)
Requirement already satisfied: av>=8.0.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (9.2.0)
Requirement already satisfied: pyside6>=6.2.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (6.2.4)
Requirement already satisfied: pyogg==0.6.14a1 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyremoteplay[gui]) (0.6.14a1)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting PyOpenGL-accelerate==3.1.5
  Using cached PyOpenGL-accelerate-3.1.5.tar.gz (538 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cffi>=1.12 in c:\users\31378\appdata\roaming\python\python310\site-packages (from cryptography>=3.4.6->pyremoteplay[gui]) (1.15.0)
Requirement already satisfied: typing-extensions in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyee>=8.1.0->pyremoteplay[gui]) (4.1.1)
Requirement already satisfied: click>=7.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (8.1.2)
Requirement already satisfied: pycryptodomex>=3.7.2 in c:\program files\python310\lib\site-packages\pycryptodomex-3.14.1-py3.10-win-amd64.egg (from pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (3.14.1)
Requirement already satisfied: construct>=2.9.45 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (2.10.68)
Requirement already satisfied: windows-curses>=2.1.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (2.3.0)
Requirement already satisfied: aiohttp>=3.5.4 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (3.8.1)
Requirement already satisfied: shiboken6==6.2.4 in c:\users\31378\appdata\roaming\python\python310\site-packages (from pyside6>=6.2.0->pyremoteplay[gui]) (6.2.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\31378\appdata\roaming\python\python310\site-packages (from requests>=2.25.1->pyremoteplay[gui]) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\31378\appdata\roaming\python\python310\site-packages (from requests>=2.25.1->pyremoteplay[gui]) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\31378\appdata\roaming\python\python310\site-packages (from requests>=2.25.1->pyremoteplay[gui]) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from requests>=2.25.1->pyremoteplay[gui]) (2.0.12)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\31378\appdata\roaming\python\python310\site-packages (from aiohttp>=3.5.4->pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (1.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from aiohttp>=3.5.4->pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (1.7.2)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\31378\appdata\roaming\python\python310\site-packages (from aiohttp>=3.5.4->pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (6.0.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\31378\appdata\roaming\python\python310\site-packages (from aiohttp>=3.5.4->pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (1.3.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\31378\appdata\roaming\python\python310\site-packages (from aiohttp>=3.5.4->pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\31378\appdata\roaming\python\python310\site-packages (from aiohttp>=3.5.4->pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (21.4.0)
Requirement already satisfied: pycparser in c:\users\31378\appdata\roaming\python\python310\site-packages (from cffi>=1.12->cryptography>=3.4.6->pyremoteplay[gui]) (2.21)
Requirement already satisfied: colorama in c:\users\31378\appdata\roaming\python\python310\site-packages (from click>=7.0->pyps4-2ndscreen>=1.2.1->pyremoteplay[gui]) (0.4.4)
Using legacy 'setup.py install' for PyOpenGL-accelerate, since package 'wheel' is not installed.
Installing collected packages: PyOpenGL-accelerate, PyOpenGL, wheel, sounddevice
  Running setup.py install for PyOpenGL-accelerate ... error
  error: subprocess-exited-with-error

  × Running setup.py install for PyOpenGL-accelerate did not run successfully.
  │ exit code: 1
  ╰─> [59 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.10
      creating build\lib.win-amd64-3.10\OpenGL_accelerate
      copying OpenGL_accelerate\__init__.py -> build\lib.win-amd64-3.10\OpenGL_accelerate
      running build_ext
      building 'OpenGL_accelerate.wrapper' extension
      creating build\temp.win-amd64-3.10
      creating build\temp.win-amd64-3.10\Release
      creating build\temp.win-amd64-3.10\Release\src
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\.. -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\src -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096 -IC:\Program Files\Python310\include -IC:\Program Files\Python310\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /Tcsrc\wrapper.c /Fobuild\temp.win-amd64-3.10\Release\src\wrapper.obj
      wrapper.c
      src\wrapper.c(6903): warning C4244: “=”: 从“Py_ssize_t”转换到“int”，可能丢失数据
      src\wrapper.c(7665): warning C4244: “=”: 从“Py_ssize_t”转换到“int”，可能丢失数据
      src\wrapper.c(25804): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      src\wrapper.c(25820): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Program Files\Python310\libs /LIBPATH:C:\Program Files\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 /EXPORT:PyInit_wrapper build\temp.win-amd64-3.10\Release\src\wrapper.obj /OUT:build\lib.win-amd64-3.10\OpenGL_accelerate\wrapper.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\src\wrapper.cp310-win_amd64.lib
        正在创建库 build\temp.win-amd64-3.10\Release\src\wrapper.cp310-win_amd64.lib 和对象 build\temp.win-amd64-3.10\Release\src\wrapper.cp310-win_amd64.exp
      正在生成代码
      已完成代码的生成
      building 'OpenGL_accelerate.formathandler' extension
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\.. -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\src -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096 -IC:\Program Files\Python310\include -IC:\Program Files\Python310\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /Tcsrc\formathandler.c /Fobuild\temp.win-amd64-3.10\Release\src\formathandler.obj
      formathandler.c
      src\formathandler.c(4658): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      src\formathandler.c(4674): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Program Files\Python310\libs /LIBPATH:C:\Program Files\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 /EXPORT:PyInit_formathandler build\temp.win-amd64-3.10\Release\src\formathandler.obj /OUT:build\lib.win-amd64-3.10\OpenGL_accelerate\formathandler.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\src\formathandler.cp310-win_amd64.lib
        正在创建库 build\temp.win-amd64-3.10\Release\src\formathandler.cp310-win_amd64.lib 和对象 build\temp.win-amd64-3.10\Release\src\formathandler.cp310-win_amd64.exp
      正在生成代码
      已完成代码的生成
      building 'OpenGL_accelerate.arraydatatype' extension
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\.. -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\src -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096 -IC:\Program Files\Python310\include -IC:\Program Files\Python310\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /Tcsrc\arraydatatype.c /Fobuild\temp.win-amd64-3.10\Release\src\arraydatatype.obj
      arraydatatype.c
      src\arraydatatype.c(20908): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      src\arraydatatype.c(20924): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Program Files\Python310\libs /LIBPATH:C:\Program Files\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 /EXPORT:PyInit_arraydatatype build\temp.win-amd64-3.10\Release\src\arraydatatype.obj /OUT:build\lib.win-amd64-3.10\OpenGL_accelerate\arraydatatype.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\src\arraydatatype.cp310-win_amd64.lib
        正在创建库 build\temp.win-amd64-3.10\Release\src\arraydatatype.cp310-win_amd64.lib 和对象 build\temp.win-amd64-3.10\Release\src\arraydatatype.cp310-win_amd64.exp
      正在生成代码
      已完成代码的生成
      building 'OpenGL_accelerate.errorchecker' extension
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\.. -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\src -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096 -IC:\Program Files\Python310\include -IC:\Program Files\Python310\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /Tcsrc\errorchecker.c /Fobuild\temp.win-amd64-3.10\Release\src\errorchecker.obj
      errorchecker.c
      src\errorchecker.c(4345): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      src\errorchecker.c(4361): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Program Files\Python310\libs /LIBPATH:C:\Program Files\Python310\PCbuild\amd64 /LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\lib\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64 /LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64 /EXPORT:PyInit_errorchecker build\temp.win-amd64-3.10\Release\src\errorchecker.obj /OUT:build\lib.win-amd64-3.10\OpenGL_accelerate\errorchecker.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.10\Release\src\errorchecker.cp310-win_amd64.lib
        正在创建库 build\temp.win-amd64-3.10\Release\src\errorchecker.cp310-win_amd64.lib 和对象 build\temp.win-amd64-3.10\Release\src\errorchecker.cp310-win_amd64.exp
      正在生成代码
      已完成代码的生成
      building 'OpenGL_accelerate.vbo' extension
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\.. -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096\src -IC:\Users\31378\AppData\Local\Temp\pip-install-ox3gj8od\pyopengl-accelerate_869b0dff5c064f12830a693e8a9c0096 -IC:\Program Files\Python310\include -IC:\Program Files\Python310\Include -IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt /Tcsrc\vbo.c /Fobuild\temp.win-amd64-3.10\Release\src\vbo.obj
      vbo.c
      src\vbo.c(11131): error C2105: “++”需要左值
      src\vbo.c(11133): error C2105: “--”需要左值
      src\vbo.c(11619): error C2105: “++”需要左值
      src\vbo.c(11621): error C2105: “--”需要左值
      src\vbo.c(13016): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      src\vbo.c(13032): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.31.31103\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> PyOpenGL-accelerate

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by ktnrg45** [comment]
Hi this should be fixed in version 0.4.2. The `PyOpenGL-accelerate` library isn't actually needed so I removed it from the requirements.
