### ISSUE TITLE
Best way to create an agent

### ISSUE THREAD

**Issue by allenwoods** [ktnrg45/pyremoteplay#3]
I found this excellent work while searching methods for GT7 credit framing. I want to wrap it into an agent so it outputs an image per second. Then, we can send back an action (key press) based on its analysis. I managed to wrap the CLI entrypoint via subprocess, but the wrapper can not fetch the stream. Is there any recommended way to do so, or will you implement such a function later?

**Comment by ktnrg45** [comment]
I've created an example of grabbing the video frames in the examples directory. You'll have to use version 0.4.3. I'll probably make docs when I have chance to cleanup the user API.

**Comment by allenwoods** [comment]
Great! Thx for the clear example
