### ISSUE TITLE
Using Playstation Controller

### ISSUE THREAD

**Issue by bleacheria** [ktnrg45/pyremoteplay#7]
This is a fantastic project. I have a question - is it possible to use a connect a Playstation controller to the PC while pyremoteplay-gui is running to control the Remote Play Host with said controller? Much like you can do with the original PS Remote Play app

If you can, is it also possible to programatically control the Remote Play client with methods such as " def button(self, name: str, action="tap", delay=0.1)" WHILE the controller is also controlling the client?

**Comment by ktnrg45** [comment]
Sounds like a great feature to add. I'll definitely look into this soon. I'm thinking that it would be possible to use the API and a controller simultaneously.

**Comment by bleacheria** [comment]
Been keeping up with the commute and I'm testing out the controller functionality and it's great! Hats off to you

I noticed that axis motion doesn't work work. Button presses get registered, but not stick movements. I'm basing this off of the gamepad.py in the examples folder and putting a while loop after gamepad instance was created.

Stick movement does get registered with the gui though
